openapi: 3.0.0
info:
  title: Test API
  description: REST APIs for managing questions for tests
  version: '1.0'

servers:
  - url: "http://localhost:3000"
    description: Local development environment

paths:
  /questions:
    get:
      operationId: get-questions
      summary: Retrieve a list of questions
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Question"
              example:
                - id: "1"
                  questionText: " If x = 3, what is the value of 2x + 5?"
                  options: ["11", "7", "9", "10"]
                  correctOption: "11"
                  difficultyLevel: "EASY"
                  section: "Quantitative"
                - id: "2"
                  questionText: "A car travels 60 miles in 1 hour. How long will it take to travel 180 miles at the same speed?"
                  options: ["2 hours", "3 hours", "4 hours", "5 hours"]
                  correctOption: "3 hours"
                  difficultyLevel: "MEDIUM"
                  section: "Quantitative"
                - id: "3"
                  questionText: "A rectangle has a length of 4x + 5 and a width of 3x - 2. If the area of the rectangle is 60 square units, what is the value of x?"
                  options: ["2", "3", "4", "5"]
                  correctOption: "3"
                  difficultyLevel: "HARD"
                  section: "Quantitative"
                - id: "4"
                  questionText: "Which of the following words is closest in meaning to happy?"
                  options: ["Joyful", "Sad", "Angry", "Bored"]
                  correctOption: "Joyful"
                  difficultyLevel: "EASY"
                  section: "Verbal"
                - id: "5"
                  questionText: "Choose the word that best completes the analogy: 'Glove is to hand as shoe is to __________.'"
                  options: ["foot", "leg", "toe", "ankle"]
                  correctOption: "foot"
                  difficultyLevel: "MEDIUM"
                  section: "Verbal"
                - id: "6"
                  questionText: "Choose the most appropriate word to complete the sentence: 'Despite the __________ nature of the problem, the team was able to reach a solution.'"
                  options: ["complex", "simple", "easy", "straightforward"]
                  correctOption: "complex"
                  difficultyLevel: "HARD"
                  section: "Verbal"
    post:
      operationId: create-question
      summary: Create a new question
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Question"
            example:
              id: "7"
              questionText: "Which of the following best describes the tone of the passage below?
              'The author’s criticism of the government’s recent policies was sharp and incisive, emphasizing its failure to address the key issues'"
              options: ["Supportive", "Critical", "Neutral", "Pessimistic"]
              correctOption: "Critical"
              difficultyLevel: "Hard"
              section: "Verbal"
      responses:
        '201':
          description: Question created successfully
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /questions/{id}:
    get:
      operationId: get-question
      summary: Retrieve a single question by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Question"
              example:
                  id: "4"
                  questionText: "Which of the following words is closest in meaning to happy?"
                  options: ["Joyful", "Sad", "Angry", "Bored"]
                  correctOption: "Joyful"
                  difficultyLevel: "EASY"
                  section: "Verbal"
        '404':
          description: Question not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    put:
      operationId: update-question
      summary: Update an existing question
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Question"
            example:
              id: "4"
              questionText: "Which of the following words is closest in meaning to sorrowful?"
              options: ["Joyful", "Sad", "Angry", "Bored"]
              correctOption: "sad"
              difficultyLevel: "EASY"
              section: "Verbal"
      responses:
        '200':
          description: Question updated successfully
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '404':
          description: Question not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    delete:
      operationId: delete-question
      summary: Delete a question by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Question deleted successfully
        '404':
          description: Question not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

 
components:
  schemas:
    Question:
      type: object
      properties:
        id:
          type: string
        questionText:
          type: string
        options:
          type: array
          items:
            type: string
        correctOption:
          type: string
        difficultyLevel:
          type: string
          enum: [EASY, MEDIUM, HARD]
        section:
          type: string
          enum: [Quantitative, Verbal]

    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
